[project]
name = "active-learning-simulations"
version = "1.0.0"
description = "Biocentral API usage for simulating active learning campaigns on protein datasets"
requires-python = "==3.12.11"
dependencies = [
    "pandas-stubs==2.3.3.251201",
    "altair>=5.3",
    "pandas>=2.2",
    "streamlit>=1.36",
    "vl-convert-python>=1.6",
    "biocentral-vis @ git+https://github.com/biocentral/biocentral_vis.git@8891271146175d196e77ff003ff4ba3fca9a15fc#subdirectory=python",
]

[tool.uv.sources]
#biocentral-api = { path = "../biocentral_api/python", editable = true }
